# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "451276576574c92822f00508e5780330"
name ="ingram-micro-dummy"
application_url = "https://ingram-micro-dummy.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_cart_transforms,read_cart_transforms,read_delivery_customizations,read_fulfillment_constraint_rules,read_inventory_shipments,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_product_feeds,read_product_listings,read_products,read_shipping,read_third_party_fulfillment_orders,write_cart_transforms,write_delivery_customizations,write_fulfillment_constraint_rules,write_inventory_shipments,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_product_feeds,write_product_listings,write_products,write_shipping,write_third_party_fulfillment_orders"

[auth]
redirect_urls =  [ "https://ingram-micro-dummy.vercel.app/auth/callback" ]